defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: watching_ht_consumer_development

test:
  <<: *defaults
  database: watching_ht_consumer_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: watching_ht_consumer
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
