twitter:
  consumer_key: 'U8uBNcmRMpPNGeeYq6g'
  consumer_secret: '0rHED7a6p4vxW4gRZ6Qrw9UMJOBbSTqCohQrk7dzHDU'
  oauth_token: '420560376-qM0CTWZrZayGPjxhdyS54GV0KOLbKZaV7F7RuydE'
  oauth_token_secret: 'nlCPuCsFeGoxNx5w2JLFJ8RhxmgPBigqQN6cwcbE9I'
